### ISSUE TITLE
better handle missing key(s)

### ISSUE THREAD

**Issue by LelandSindt** [LelandSindt/teslacam#2]
-- Logs begin at Mon 2019-01-07 07:14:55 CST. --
Jan 07 07:15:15 teslapi systemd[1]: Started Power Monitor.
Jan 07 07:16:08 teslapi powermonitor.py[487]: Traceback (most recent call last):
Jan 07 07:16:08 teslapi powermonitor.py[487]:   File "/home/pi/powermonitor.py", line 13, in <module>
Jan 07 07:16:08 teslapi powermonitor.py[487]:     sys.stdout.write(time.strftime("%Y-%m-%d %H:%M") + " Charge State: " + pj.status.GetStatus()['data']['powerInput5vIo'] + " Charge Percent: " +  str(pj.status.GetChargeLevel()['data']) + " Power Loss Count: " + str(powerloss) + "\n")
Jan 07 07:16:08 teslapi powermonitor.py[487]: KeyError: 'data'
Jan 07 07:16:09 teslapi systemd[1]: powermonitor.service: Main process exited, code=exited, status=1/FAILURE
Jan 07 07:16:09 teslapi systemd[1]: powermonitor.service: Unit entered failed state.
Jan 07 07:16:09 teslapi systemd[1]: powermonitor.service: Failed with result 'exit-code'.

**Comment by LelandSindt** [comment]
another example

Mar 18 07:58:02 teslapi systemd[1]: Started Power Monitor.
Mar 18 07:58:34 teslapi powermonitor.py[380]: Traceback (most recent call last):
Mar 18 07:58:34 teslapi powermonitor.py[380]:   File "/home/pi/powermonitor.py", line 13, in <module>
Mar 18 07:58:34 teslapi powermonitor.py[380]:     sys.stdout.write(time.strftime("%Y-%m-%d %H:%M") + " Charge State: " + pj.status.GetStatus()['data']['powerInput5vIo'] + " Charge Percent: " +  str(pj.status.GetChargeLevel()['data']) + " Power Loss Count
Mar 18 07:58:34 teslapi powermonitor.py[380]: KeyError: 'data'
Mar 18 07:58:35 teslapi systemd[1]: powermonitor.service: Main process exited, code=exited, status=1/FAILURE
Mar 18 07:58:35 teslapi systemd[1]: powermonitor.service: Unit entered failed state.
Mar 18 07:58:35 teslapi systemd[1]: powermonitor.service: Failed with result 'exit-code'.
